server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
      gateway:
        routes:
          - id: LOCATION-SERVICE
            uri: http//localhost:9090
            predicates:
              - Path=/results

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka